#ifndef LIBEMBROIDERY_HEADER__
#define LIBEMBROIDERY_HEADER__

#include "emb-arc.h"
#include "emb-circle.h"
#include "emb-color.h"
#include "emb-compress.h"
#include "emb-ellipse.h"
#include "emb-file.h"
#include "emb-flag.h"
#include "emb-format.h"
#include "emb-hash.h"
#include "emb-hoop.h"
#include "emb-layer.h"
#include "emb-line.h"
#include "emb-logging.h"
#include "emb-outline.h"
#include "emb-path.h"
#include "emb-pattern.h"
#include "emb-point.h"
#include "emb-polygon.h"
#include "emb-polyline.h"
#include "emb-reader-writer.h"
#include "emb-rect.h"
#include "emb-satin-line.h"
#include "emb-settings.h"
#include "emb-spline.h"
#include "emb-stitch.h"
#include "emb-thread.h"
#include "emb-time.h"
#include "emb-vector.h"
#include "thread-color.h"
#include "formats.h"

#endif
