#############################################################################
# Makefile for building: libembroidery
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  libembroidery.pro
# Template: subdirs
# Command: E:\Qt\5.6\msvc2015_64\bin\qmake.exe -o Makefile libembroidery.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = E:\Qt\5.6\msvc2015_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-libembroidery-shared-pro \
		sub-libembroidery-static-pro


sub-libembroidery-shared-pro-qmake_all:  FORCE
	$(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f Makefile.libembroidery-shared qmake_all
sub-libembroidery-shared-pro: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared
sub-libembroidery-shared-pro-make_first-ordered: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared 
sub-libembroidery-shared-pro-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared 
sub-libembroidery-shared-pro-all-ordered: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared all
sub-libembroidery-shared-pro-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared all
sub-libembroidery-shared-pro-clean-ordered: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared clean
sub-libembroidery-shared-pro-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared clean
sub-libembroidery-shared-pro-distclean-ordered: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared distclean
sub-libembroidery-shared-pro-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared distclean
sub-libembroidery-shared-pro-install_subtargets-ordered: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared install
sub-libembroidery-shared-pro-install_subtargets: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared install
sub-libembroidery-shared-pro-uninstall_subtargets-ordered: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared uninstall
sub-libembroidery-shared-pro-uninstall_subtargets: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared uninstall
sub-libembroidery-static-pro-qmake_all: sub-libembroidery-shared-pro-qmake_all FORCE
	$(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f Makefile.libembroidery-static qmake_all
sub-libembroidery-static-pro: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static
sub-libembroidery-static-pro-make_first-ordered: sub-libembroidery-shared-pro-make_first-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static 
sub-libembroidery-static-pro-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static 
sub-libembroidery-static-pro-all-ordered: sub-libembroidery-shared-pro-all-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static all
sub-libembroidery-static-pro-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static all
sub-libembroidery-static-pro-clean-ordered: sub-libembroidery-shared-pro-clean-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static clean
sub-libembroidery-static-pro-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static clean
sub-libembroidery-static-pro-distclean-ordered: sub-libembroidery-shared-pro-distclean-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static distclean
sub-libembroidery-static-pro-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static distclean
sub-libembroidery-static-pro-install_subtargets-ordered: sub-libembroidery-shared-pro-install_subtargets-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static install
sub-libembroidery-static-pro-install_subtargets: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static install
sub-libembroidery-static-pro-uninstall_subtargets-ordered: sub-libembroidery-shared-pro-uninstall_subtargets-ordered  FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static uninstall
sub-libembroidery-static-pro-uninstall_subtargets: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static uninstall

Makefile: libembroidery.pro ..\..\Qt\5.6\msvc2015_64\mkspecs\win32-msvc2015\qmake.conf ..\..\Qt\5.6\msvc2015_64\mkspecs\features\spec_pre.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\common\angle.conf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\common\msvc-base.conf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\common\msvc-desktop.conf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\qconfig.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3drender.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axbase.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axserver.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_clucene_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_core.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_core_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_dbus.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_designer.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_gui.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_help.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_help_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_labscontrols_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_labstemplates_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_location.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_location_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_network.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_network_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_nfc.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_opengl.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_platformsupport_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_positioning.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qml.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quick.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_script.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_script_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sensors.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialport.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sql.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_svg.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_testlib.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_uitools.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webengine.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webengine_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginecore.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_websockets.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webview.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_widgets.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_winextras.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_winextras_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xml.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\qt_functions.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\qt_config.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\win32\qt_config.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\win32-msvc2015\qmake.conf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\spec_post.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\exclusive_builds.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\default_pre.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\win32\default_pre.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\resolve_config.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\exclusive_builds_post.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\default_post.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\win32\rtti.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\precompile_header.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\warn_on.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\win32\windows.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\testcase_targets.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\exceptions.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\yacc.prf \
		..\..\Qt\5.6\msvc2015_64\mkspecs\features\lex.prf \
		libembroidery.pro
	$(QMAKE) -o Makefile libembroidery.pro
..\..\Qt\5.6\msvc2015_64\mkspecs\features\spec_pre.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\common\angle.conf:
..\..\Qt\5.6\msvc2015_64\mkspecs\common\msvc-base.conf:
..\..\Qt\5.6\msvc2015_64\mkspecs\common\msvc-desktop.conf:
..\..\Qt\5.6\msvc2015_64\mkspecs\qconfig.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dcore.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dinput.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquick.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3drender.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axbase.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axserver.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_clucene_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_concurrent.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_core.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_core_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_dbus.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_designer.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_designer_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_gui.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_gui_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_help.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_help_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_labscontrols_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_labstemplates_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_location.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_location_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimedia.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_network.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_network_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_nfc.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_opengl.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_positioning.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_printsupport.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qml.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qml_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qmltest.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quick.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quick_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_script.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_script_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_scripttools.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sensors.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialbus.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialport.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sql.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_sql_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_svg.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_svg_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_testlib.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_uitools.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webchannel.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webengine.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webengine_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginecore.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_websockets.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webview.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_webview_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_widgets.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_winextras.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xml.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xml_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\qt_functions.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\qt_config.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\win32\qt_config.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\win32-msvc2015\qmake.conf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\spec_post.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\exclusive_builds.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\default_pre.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\win32\default_pre.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\resolve_config.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\exclusive_builds_post.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\default_post.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\win32\rtti.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\precompile_header.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\warn_on.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\win32\windows.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\testcase_targets.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\exceptions.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\yacc.prf:
..\..\Qt\5.6\msvc2015_64\mkspecs\features\lex.prf:
libembroidery.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile libembroidery.pro

qmake_all: sub-libembroidery-shared-pro-qmake_all sub-libembroidery-static-pro-qmake_all FORCE

make_first: sub-libembroidery-shared-pro-make_first-ordered sub-libembroidery-static-pro-make_first-ordered  FORCE
all: sub-libembroidery-shared-pro-all-ordered sub-libembroidery-static-pro-all-ordered  FORCE
clean: sub-libembroidery-shared-pro-clean-ordered sub-libembroidery-static-pro-clean-ordered  FORCE
distclean: sub-libembroidery-shared-pro-distclean-ordered sub-libembroidery-static-pro-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) object_script.*
install_subtargets: sub-libembroidery-shared-pro-install_subtargets-ordered sub-libembroidery-static-pro-install_subtargets-ordered FORCE
uninstall_subtargets: sub-libembroidery-shared-pro-uninstall_subtargets-ordered sub-libembroidery-static-pro-uninstall_subtargets-ordered FORCE

sub-libembroidery-shared-pro-debug_ordered:
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared debug
sub-libembroidery-static-pro-debug_ordered: sub-libembroidery-shared-pro-debug_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static debug
debug: sub-libembroidery-shared-pro-debug_ordered sub-libembroidery-static-pro-debug_ordered

sub-libembroidery-shared-pro-release_ordered:
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared release
sub-libembroidery-static-pro-release_ordered: sub-libembroidery-shared-pro-release_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static release
release: sub-libembroidery-shared-pro-release_ordered sub-libembroidery-static-pro-release_ordered

sub-libembroidery-shared-pro-check_ordered:
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-shared $(QMAKE) E:\Products\libembroidery\libembroidery-shared.pro -o Makefile.libembroidery-shared ) && $(MAKE) -f Makefile.libembroidery-shared check
sub-libembroidery-static-pro-check_ordered: sub-libembroidery-shared-pro-check_ordered 
	@set MAKEFLAGS=$(MAKEFLAGS)
	( if not exist Makefile.libembroidery-static $(QMAKE) E:\Products\libembroidery\libembroidery-static.pro -o Makefile.libembroidery-static ) && $(MAKE) -f Makefile.libembroidery-static check
check: sub-libembroidery-shared-pro-check_ordered sub-libembroidery-static-pro-check_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

