CC := gcc
INC_DIRS := -Iinclude
CFLAGS := -std=c99 $(INC_DIRS)
# -Werror -pedantic
LIBRARY := libembroidery.so
EXEC := sew
BUILD_DIR := build
LIB_FLAGS := -shared
LDFLAGS := -lm
LIB_SOURCES := \
src/array.c \
src/compress.c \
src/data.c \
src/encoding.c \
src/file.c \
src/fill.c \
src/geometry.c \
src/image.c \
src/pattern.c \
src/string.c \
src/thread_colors.c \
src/thread.c \
\
src/formats/100.c \
src/formats/10o.c \
src/formats/art.c \
src/formats/bmc.c \
src/formats/bro.c \
src/formats/cnd.c \
src/formats/col.c \
src/formats/csd.c \
src/formats/csv.c \
src/formats/dat.c \
src/formats/dsb.c \
src/formats/dst.c \
src/formats/dsz.c \
src/formats/dxf.c \
src/formats/edr.c \
src/formats/emd.c \
src/formats/exy.c \
src/formats/eys.c \
src/formats/fxy.c \
src/formats/gc.c \
src/formats/gnc.c \
src/formats/gt.c \
src/formats/hus.c \
src/formats/inb.c \
src/formats/jef.c \
src/formats/ksm.c \
src/formats/mit.c \
src/formats/new.c \
src/formats/ofm.c \
src/formats/pcd.c \
src/formats/pcm.c \
src/formats/pcq.c \
src/formats/pcs.c \
src/formats/pes.c \
src/formats/plt.c \
src/formats/rgb.c \
src/formats/sew.c \
src/formats/shv.c \
src/formats/sst.c \
src/formats/stx.c \
src/formats/svg.c \
src/formats/t09.c \
src/formats/tap.c \
src/formats/thr.c \
src/formats/txt.c \
src/formats/u00.c \
src/formats/u01.c \
src/formats/vip.c \
src/formats/vp3.c \
src/formats/xxx.c \
src/formats/zsk.c \
\
src/geometry/arc.c \
src/geometry/circle.c \
src/geometry/ellipse.c \
src/geometry/line.c \
src/geometry/polygon.c \
src/geometry/vector.c \
\
src/test/arc.c \
src/test/circle.c \
src/test/convert.c \
src/test/ellipse.c \
src/test/fill.c \
src/test/format_table.c \
src/test/render.c \
src/test/test.c \
src/test/thread_color.c \
src/test/vector.c
SOURCES := $(LIB_SOURCES) src/sew.c

LIB_OBJECTS := $(LIB_SOURCES:%=$(BUILD_DIR)/%.o)
SEW_OBJECTS := $(LIB_OBJECTS) src/sew.o

all: $(BUILD_DIR)/$(LIBRARY) $(BUILD_DIR)/$(EXEC)

$(BUILD_DIR)/$(LIBRARY): $(LIB_OBJECTS)
	$(CC) $(LIB_FLAGS) $(LIB_OBJECTS) -o $@

$(BUILD_DIR)/$(EXEC): $(SEW_OBJECTS)
	$(CC) $(SEW_OBJECTS) -o $@ $(LDFLAGS)

$(BUILD_DIR)/%.c.o: %.c
	mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -fPIC -c $< -o $@

install:
	mv $(BUILD_DIR)/$(EXEC) /usr/bin
	mv $(BUILD_DIR)/$(LIBRARY) /usr/bin/x86_64-linux-gnu

test: $(BUILD_DIR)/$(EXEC)
	./$(BUILD_DIR)/$(EXEC) --test

.PHONY: clean
clean:
	rm -fr $(BUILD_DIR)
