site_name: "libembroidery: A low-level embroidery format library"
repo_url: "https://github.com/Embroidermodder/libembroidery/"
site_url: "http://embroidermodder.org/libembroidery/"
edit_uri: 'tree/master/docs_src/'
docs_dir: "docs_src/"
site_dir: "docs/"
theme:
  name: "material"
nav:
  - Overview: 'README.md'
  - Formats:
    - Overview: 'formats/overview.md'
    - 100: 'formats/100_format.md'
    - 10o: 'formats/10o_format.md'
    - art: 'formats/art_format.md'
    - bmc: 'formats/bmc_format.md'
    - bro: 'formats/bro_format.md'
    - cnd: 'formats/cnd_format.md'
    - col: 'formats/col_format.md'
    - csd: 'formats/csd_format.md'
    - csv: 'formats/csv_format.md'
    - dat: 'formats/dat_format.md'
    - dem: 'formats/dem_format.md'
    - dsb: 'formats/dsb_format.md'
    - dst: 'formats/dst_format.md'
    - dsz: 'formats/dsz_format.md'
    - dxf: 'formats/dxf_format.md'
    - edr: 'formats/edr_format.md'
    - emd: 'formats/emd_format.md'
    - exp: 'formats/exp_format.md'
    - exy: 'formats/exy_format.md'
    - eys: 'formats/eys_format.md'
    - fxy: 'formats/fxy_format.md'
    - fxy: 'formats/fxy_format.md'
    - gnc: 'formats/gnc_format.md'
    - gt: 'formats/gt_format.md'
    - hus: 'formats/hus_format.md'
    - inb: 'formats/inb_format.md'
    - inf: 'formats/inf_format.md'
    - jef: 'formats/jef_format.md'
    - ksm: 'formats/ksm_format.md'
    - max: 'formats/max_format.md'
    - mit: 'formats/mit_format.md'
    - new: 'formats/new_format.md'
    - ofm: 'formats/ofm_format.md'
    - pcd: 'formats/pcd_format.md'
    - pcm: 'formats/pcm_format.md'
    - pcq: 'formats/pcq_format.md'
    - pcs: 'formats/pcs_format.md'
    - pec: 'formats/pec_format.md'
    - pel: 'formats/pel_format.md'
    - pem: 'formats/pem_format.md'
    - pes: 'formats/pes_format.md'
    - phb: 'formats/phb_format.md'
    - phc: 'formats/phc_format.md'
    - plt: 'formats/plt_format.md'
    - rgb: 'formats/rgb_format.md'
    - sew: 'formats/sew_format.md'
    - shv: 'formats/shv_format.md'
    - sst: 'formats/sst_format.md'
    - stx: 'formats/stx_format.md'
    - svg: 'formats/svg_format.md'
    - t01: 'formats/t01_format.md'
    - t09: 'formats/t09_format.md'
    - tap: 'formats/tap_format.md'
    - thr: 'formats/thr_format.md'
    - txt: 'formats/txt_format.md'
    - u00: 'formats/u00_format.md'
    - u01: 'formats/u01_format.md'
    - vip: 'formats/vip_format.md'
    - vp3: 'formats/vp3_format.md'
    - xxx: 'formats/xxx_format.md'
    - zsk: 'formats/zsk_format.md'
  - Development:
    - Contributing: 'contributing.md'
    - Style Guide: 'libembroidery_style.md'
markdown_extensions:
  - mdx_truly_sane_lists
  - pymdownx.superfences
  - pymdownx.arithmatex:
        generic: true
  - footnotes
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - exclude:
      glob: BUILD
  - search