%include "string_table.asm"

svg_property_token_table:
	dd	audio_level_token
	dd	buffered_rendering_token
	dd	color_token
	dd	color_rendering_token
	dd	direction_token
	dd	display_token
	dd	display_align_token
	dd	fill_token
	dd	fill_opacity_token
	dd	fill_rule_token
	dd	font_family_token
	dd	font_size_token
	dd	font_style_token
	dd	font_variant_token
	dd	font_weight_token
	dd	image_rendering_token
	dd	line_increment_token
	dd	opacity_token
	dd	pointer_events_token
	dd	shape_rendering_token
	dd	solid_color_token
	dd	solid_opacity_token
	dd	stop_color_token
	dd	stop_opacity_token
	dd	stroke_token
	dd	stroke_dasharray_token
	dd	stroke_linecap_token
	dd	stroke_linejoin_token
	dd	stroke_miterlimit_token
	dd	stroke_opacity_token
	dd	stroke_width_token
	dd	text_align_token
	dd	text_anchor_token
	dd	text_rendering_token
	dd	unicode_bidi_token
	dd	vector_effect_token
	dd	viewport_fill_token
	dd	viewport_fill_opacity_token
	dd	visibility_token
	dd	0


svg_attribute_token_table:
	dd	about_token
	dd	accent_height_token
	dd	accumulate_token
	dd	additive_token
	dd	alphabetic_token
	dd	arabic_form_token
	dd	ascent_token
	dd	attribute_name_token
	dd	attribute_type_token
	dd	bandwidth_token
	dd	base_profile_token
	dd	bbox_token
	dd	begin_token
	dd	by_token
	dd	calc_mode_token
	dd	cap_height_token
	dd	class_token
	dd	content_token
	dd	content_script_type_token
	dd	cx_token
	dd	cy_token
	dd	d_token
	dd	datatype_token
	dd	default_action_token
	dd	descent_token
	dd	dur_token
	dd	editable_token
	dd	end_token
	dd	ev_event_token
	dd	event_token
	dd	external_resources_required_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	font_family_token
	dd	font_stretch_token
	dd	font_style_token
	dd	font_variant_token
	dd	font_weight_token
	dd	from_token
	dd	g1_token
	dd	g2_token
	dd	glyph_name_token
	dd	gradient_units_token
	dd	handler_token
	dd	hanging_token
	dd	height_token
	dd	horiz_adv_x_token
	dd	horiz_origin_x_token
	dd	id_token
	dd	ideographic_token
	dd	initial_visibility_token
	dd	k_token
	dd	key_points_token
	dd	key_splines_token
	dd	key_times_token
	dd	lang_token
	dd	mathematical_token
	dd	max_token
	dd	media_character_encoding_token
	dd	media_content_encoding_token
	dd	media_size_token
	dd	media_time_token
	dd	min_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	observer_token
	dd	offset_token
	dd	origin_token
	dd	overlay_token
	dd	overline_position_token
	dd	overline_thickness_token
	dd	panose_1_token
	dd	path_token
	dd	path_length_token
	dd	phase_token
	dd	playback_order_token
	dd	points_token
	dd	preserve_aspect_ratio_token
	dd	propagate_token
	dd	property_token
	dd	r_token
	dd	rel_token
	dd	repeat_count_token
	dd	repeat_dur_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	restart_token
	dd	rev_token
	dd	role_token
	dd	rotate_token
	dd	rx_token
	dd	ry_token
	dd	slope_token
	dd	snapshot_time_token
	dd	stemh_token
	dd	stemv_token
	dd	strikethrough_position_token
	dd	strikethrough_thickness_token
	dd	sync_behavior_token
	dd	sync_behavior_default_token
	dd	sync_master_token
	dd	sync_tolerance_token
	dd	sync_tolerance_default_token
	dd	system_language_token
	dd	target_token
	dd	timeline_begin_token
	dd	to_token
	dd	transform_token
	dd	transform_behavior_token
	dd	type_token
	dd	typeof_token
	dd	u1_token
	dd	u2_token
	dd	underline_position_token
	dd	underline_thickness_token
	dd	unicode_token
	dd	unicode_range_token
	dd	units_per_em_token
	dd	values_token
	dd	version_token
	dd	viewbox_token
	dd	width_token
	dd	widths_token
	dd	x_token
	dd	x_height_token
	dd	x1_token
	dd	x2_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	y_token
	dd	y1_token
	dd	y2_token
	dd	zoom_and_pan_token
	dd	slash_token
	dd	0


solid_color_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0

stop_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	id_token
	dd	offset_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0

svg_token_table:
	dd	about_token
	dd	base_profile_token
	dd	class_token
	dd	content_token
	dd	content_script_type_token
	dd	datatype_token
	dd	external_resources_required_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	height_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	playback_order_token
	dd	preserve_aspect_ratio_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	snapshot_time_token
	dd	sync_behavior_default_token
	dd	sync_tolerance_default_token
	dd	timeline_begin_token
	dd	typeof_token
	dd	version_token
	dd	viewbox_token
	dd	width_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	zoom_and_pan_token
	dd	slash_token
	dd	0


inkscape_token_table:
	dd	xmlns_dc_token
	dd	xmlns_cc_token
	dd	xmlns_rdf_token
	dd	xmlns_svg_token
	dd	xmlns_token
	dd	0


svg_element_token_table:
	dd	xml_token
	dd	a_token
	dd	animate_token
	dd	animate_color_token
	dd	animate_motion_token
	dd	animate_transform_token
	dd	animation_token
	dd	audio_token
	dd	circle_token
	dd	defs_token
	dd	desc_token
	dd	discard_token
	dd	ellipse_token
	dd	font_token
	dd	font_face_token
	dd	font_face_src_token
	dd	font_face_uri_token
	dd	foreign_object_token
	dd	g_token
	dd	glyph_token
	dd	handler_token
	dd	hkern_token
	dd	image_token
	dd	line_token
	dd	linear_gradient_token
	dd	listener_token
	dd	metadata_token
	dd	missing_glyph_token
	dd	mpath_token
	dd	path_token
	dd	polygon_token
	dd	polyline_token
	dd	prefetch_token
	dd	radial_gradient_token
	dd	rect_token
	dd	script_token
	dd	set_token
	dd	solid_color_token
	dd	stop_token
	dd	svg_token
	dd	switch_token
	dd	tbreak_token
	dd	text_token
	dd	text_area_token
	dd	title_token
	dd	tspan_token
	dd	use_token
	dd	video_token
	dd	0

;	_tODO: not implemented _sVG _full 1.1 _spec _elements
%if 0
not_implemented_svg_tokens:
	dd	alt_glyph_token
	dd	alt_glyph_def_token
	dd	altGlyphItem_token
	dd	clip_path_token
	dd	color_profile_token
	dd	cursor_token
	dd	feBlend_token
	dd	fe_colorMatrix_token
	dd	fe_component_transfer_token
	dd	fe_composite_token
	dd	fe_convolveMatrix_token
	dd	feDiffuse_lighting_token
	dd	feDisplacementMap_token
	dd	feDistant_light_token
	dd	fe_flood_token
	dd	fe_funcA_token
	dd	fe_funcB_token
	dd	fe_funcG_token
	dd	fe_funcR_token
	dd	feGaussianBlur_token
	dd	feImage_token
	dd	feMerge_token
	dd	feMergeNode_token
	dd	feMorphology_token
	dd	feOffset_token
	dd	fe_point_light_token
	dd	fe_specular_lighting_token
	dd	fe_spot_light_token
	dd	fe_tile_token
	dd	fe_turbulence_token
	dd	filter
	dd	font_face_format_token
	dd	font_face_name_token
	dd	glyphRef_token
	dd	marker_token
	dd	mask_token
	dd	pattern_token
	dd	style_token
	dd	symbol_token
	dd	text_path_token
	dd	tref_token
	dd	view_token
	dd	vkern_token
	dd	0
%endif


svg_media_property_token_table:
	dd	audio_level_token
	dd	buffered_rendering_token
	dd	display_token
	dd	image_rendering_token
	dd	pointer_events_token
	dd	shape_rendering_token
	dd	text_rendering_token
	dd	viewport_fill_token
	dd	viewport_fill_opacity_token
	dd	visibility_token
	dd	0


xml_token_table:
	dd	encoding_token
	dd	standalone_token
	dd	version_token
	dd	slash_token
	dd	0


link_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	external_resources_required_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	target_token
	dd	transform_token
	dd	typeof_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


animate_token_table:
	dd	about_token
	dd	accumulate_token
	dd	additive_token
	dd	attribute_name_token
	dd	attribute_type_token
	dd	begin_token
	dd	by_token
	dd	calc_mode_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	dur_token
	dd	end_token
	dd	fill_token
	dd	from_token
	dd	id_token
	dd	key_splines_token
	dd	key_times_token
	dd	max_token
	dd	min_token
	dd	property_token
	dd	rel_token
	dd	repeat_count_token
	dd	repeat_dur_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	restart_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	to_token
	dd	typeof_token
	dd	values_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


animate_color_token_table:
	dd	about_token
	dd	accumulate_token
	dd	additive_token
	dd	attribute_name_token
	dd	attribute_type_token
	dd	begin_token
	dd	by_token
	dd	calc_mode_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	dur_token
	dd	end_token
	dd	fill_token
	dd	from_token
	dd	id_token
	dd	key_splines_token
	dd	key_times_token
	dd	max_token
	dd	min_token
	dd	property_token
	dd	rel_token
	dd	repeat_count_token
	dd	repeat_dur_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	restart_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	to_token
	dd	typeof_token
	dd	values_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


animate_motion_token_table:
	dd	about_token
	dd	accumulate_token
	dd	additive_token
	dd	begin_token
	dd	by_token
	dd	calc_mode_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	dur_token
	dd	end_token
	dd	fill_token
	dd	from_token
	dd	id_token
	dd	key_points_token
	dd	key_splines_token
	dd	key_times_token
	dd	max_token
	dd	min_token
	dd	origin_token
	dd	path_token
	dd	property_token
	dd	rel_token
	dd	repeat_count_token
	dd	repeat_dur_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	restart_token
	dd	rev_token
	dd	role_token
	dd	rotate_token
	dd	system_language_token
	dd	to_token
	dd	typeof_token
	dd	values_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


animate_transform_token_table:
	dd	about_token
	dd	accumulate_token
	dd	additive_token
	dd	attribute_name_token
	dd	attribute_type_token
	dd	begin_token
	dd	by_token
	dd	calc_mode_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	dur_token
	dd	end_token
	dd	fill_token
	dd	from_token
	dd	id_token
	dd	key_splines_token
	dd	key_times_token
	dd	max_token
	dd	min_token
	dd	property_token
	dd	rel_token
	dd	repeat_count_token
	dd	repeat_dur_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	restart_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	to_token
	dd	type_token
	dd	typeof_token
	dd	values_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


animation_token_table:
	dd	about_token
	dd	begin_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	dur_token
	dd	end_token
	dd	external_resources_required_token
	dd	fill_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	height_token
	dd	id_token
	dd	initial_visibility_token
	dd	max_token
	dd	min_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	preserve_aspect_ratio_token
	dd	property_token
	dd	rel_token
	dd	repeat_count_token
	dd	repeat_dur_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	restart_token
	dd	rev_token
	dd	role_token
	dd	sync_behavior_token
	dd	sync_master_token
	dd	sync_tolerance_token
	dd	system_language_token
	dd	transform_token
	dd	typeof_token
	dd	width_token
	dd	x_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	y_token
	dd	slash_token
	dd	0


audio_token_table:
	dd	about_token
	dd	begin_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	dur_token
	dd	end_token
	dd	external_resources_required_token
	dd	fill_token
	dd	id_token
	dd	max_token
	dd	min_token
	dd	property_token
	dd	rel_token
	dd	repeat_count_token
	dd	repeat_dur_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	restart_token
	dd	rev_token
	dd	role_token
	dd	sync_behavior_token
	dd	sync_master_token
	dd	sync_tolerance_token
	dd	system_language_token
	dd	type_token
	dd	typeof_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


circle_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	cx_token
	dd	cy_token
	dd	datatype_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	property_token
	dd	r_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	transform_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


defs_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


desc_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


discard_token_table:
	dd	about_token
	dd	begin_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	db	system_language_token
	dd	typeof_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	db	xlink_role_token
	db	xlink_show_token
	db	xlink_title_token
	db	xlink_type_token
	db	xml_base_token
	db	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


ellipse_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	cx_token
	dd	cy_token
	dd	datatype_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	rx_token
	dd	ry_token
	dd	system_language_token
	dd	transform_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


font_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	external_resources_required_token
	dd	horiz_adv_x_token
	dd	horiz_origin_x_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


font_face_token_table:
	dd	about_token
	dd	accent_height_token
	dd	alphabetic_token
	dd	ascent_token
	dd	bbox_token
	dd	cap_height_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	descent_token
	dd	external_resources_required_token
	dd	font_family_token
	dd	font_stretch_token
	dd	font_style_token
	dd	font_variant_token
	dd	font_weight_token
	dd	hanging_token
	dd	id_token
	dd	ideographic_token
	dd	mathematical_token
	dd	overline_position_token
	dd	overline_thickness_token
	dd	panose_1_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	slope_token
	dd	stemh_token
	dd	stemv_token
	dd	strikethrough_position_token
	dd	strikethrough_thickness_token
	dd	typeof_token
	dd	underline_position_token
	dd	underline_thickness_token
	dd	unicode_range_token
	dd	units_per_em_token
	dd	widths_token
	dd	x_height_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


font_face_src_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


font_face_uri_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	external_resources_required_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	typeof_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


foreign_object_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	external_resources_required_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	height_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	transform_token
	dd	typeof_token
	dd	width_token
	dd	x_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	y_token
	dd	slash_token
	dd	0


group_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	external_resources_required_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	transform_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


glyph_token_table:
	dd	about_token
	dd	arabic_form_token
	dd	class_token
	dd	content_token
	dd	d_token
	dd	datatype_token
	dd	glyph_name_token
	dd	horiz_adv_x_token
	dd	id_token
	dd	lang_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	typeof_token
	dd	unicode_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


handler_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	ev_event_token
	dd	external_resources_required_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	type_token
	dd	typeof_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


hkern_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	g1_token
	dd	g2_token
	dd	id_token
	dd	k_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	typeof_token
	dd	u1_token
	dd	u2_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


image_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	external_resources_required_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	height_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	opacity_token
	dd	preserve_aspect_ratio_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	transform_token
	dd	type_token
	dd	typeof_token
	dd	width_token
	dd	x_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	y_token
	dd	slash_token
	dd	0


line_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	transform_token
	dd	typeof_token
	dd	x1_token
	dd	x2_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	y1_token
	dd	y2_token
	dd	slash_token
	dd	0


linear_gradient_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	gradient_units_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	typeof_token
	dd	x1_token
	dd	x2_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	y1_token
	dd	y2_token
	dd	slash_token
	dd	0


listener_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	default_action_token
	dd	event_token
	dd	handler_token
	dd	id_token
	dd	observer_token
	dd	phase_token
	dd	propagate_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	target_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


metadata_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


missing_glyph_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	d_token
	dd	datatype_token
	dd	horiz_adv_x_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


mpath_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	typeof_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


path_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	d_token
	dd	datatype_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	path_length_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	transform_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


polygon_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	points_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	transform_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


polyline_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	points_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	transform_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


prefetch_token_table:
	dd	about_token
	dd	bandwidth_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	id_token
	dd	media_character_encoding_token
	dd	media_content_encoding_token
	dd	media_size_token
	dd	media_time_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	typeof_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


radial_gradient_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	cx_token
	dd	cy_token
	dd	datatype_token
	dd	gradient_units_token
	dd	id_token
	dd	property_token
	dd	r_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


rect_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	height_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	rx_token
	dd	ry_token
	dd	system_language_token
	dd	transform_token
	dd	typeof_token
	dd	width_token
	dd	x_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	y_token
	dd	slash_token
	dd	0


script_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	external_resources_required_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	type_token
	dd	typeof_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


set_token_table:
	dd	about_token
	dd	attribute_name_token
	dd	attribute_type_token
	dd	begin_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	dur_token
	dd	end_token
	dd	fill_token
	dd	id_token
	dd	max_token
	dd	min_token
	dd	property_token
	dd	rel_token
	dd	repeat_count_token
	dd	repeat_dur_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	to_token
	dd	typeof_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


switch_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	external_resources_required_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	transform_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


tbreak_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


text_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	editable_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	rotate_token
	dd	system_language_token
	dd	transform_token
	dd	typeof_token
	dd	x_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	y_token
	dd	slash_token
	dd	0


text_area_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	editable_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	height_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	transform_token
	dd	typeof_token
	dd	width_token
	dd	x_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	y_token
	dd	slash_token
	dd	0


title_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	id_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


tspan_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	typeof_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	slash_token
	dd	0


use_token_table:
	dd	about_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	external_resources_required_token
	dd	focus_highlight_token
	dd	focusable_token
	dd	id_token
	dd	nav_down_token
	dd	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	property_token
	dd	rel_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	rev_token
	dd	role_token
	dd	system_language_token
	dd	transform_token
	dd	typeof_token
	dd	x_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	db	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	y_token
	dd	slash_token
	dd	0

video_token_table:
	dd	about_token
	dd	begin_token
	dd	class_token
	dd	content_token
	dd	datatype_token
	dd	dur_token
	dd	end_token
	db	external_resources_required_token
	db	fill_token
	db	focus_highlight_token
	db	focusable_token
	db	height_token
	db	id_token
	db	initial_visibility_token
	db	max_token
	db	min_token
	db	nav_down_token
	db	nav_down_left_token
	dd	nav_down_right_token
	dd	nav_left_token
	dd	nav_next_token
	dd	nav_prev_token
	dd	nav_right_token
	dd	nav_up_token
	dd	nav_up_left_token
	dd	nav_up_right_token
	dd	overlay_token
	dd	preserve_aspect_ratio_token
	dd	property_token
	dd	rel_token
	dd	repeat_count_token
	dd	repeat_dur_token
	dd	required_extensions_token
	dd	required_features_token
	dd	required_fonts_token
	dd	required_formats_token
	dd	resource_token
	dd	restart_token
	dd	rev_token
	dd	role_token
	dd	sync_behavior_token
	dd	sync_master_token
	dd	sync_tolerance_token
	dd	system_language_token
	dd	transform_token
	dd	transform_behavior_token
	dd	type_token
	dd	typeof_token
	dd	width_token
	dd	x_token
	dd	xlink_actuate_token
	dd	xlink_arcrole_token
	dd	xlink_href_token
	dd	xlink_role_token
	dd	xlink_show_token
	dd	xlink_title_token
	dd	xlink_type_token
	dd	xml_base_token
	dd	xml_id_token
	dd	xml_lang_token
	dd	xml_space_token
	dd	y_token
	dd	slash_token
	dd	0


svg_token_lists:
	dd	xml_token_table
	dd	link_token_table
	dd	animate_token_table
	dd	animate_color_token_table
	dd	animate_motion_token_table
	dd	animate_transform_token_table
	dd	animation_token_table
	dd	audio_token_table
	dd	circle_token_table
	dd	defs_token_table
	dd	desc_token_table
	dd	discard_token_table
	dd	ellipse_token_table
	dd	font_token_table
	dd	font_face_token_table
	dd	font_face_src_token_table
	dd	font_face_uri_token_table
	dd	foreign_object_token_table
	dd	group_token_table
	dd	glyph_token_table
	dd	handler_token_table
	dd	hkern_token_table
	dd	image_token_table
	dd	line_token_table
	dd	linear_gradient_token_table
	dd	listener_token_table
	dd	metadata_token_table
	dd	missing_glyph_token_table
	dd	mpath_token_table
	dd	path_token_table
	dd	polygon_token_table
	dd	polyline_token_table
	dd	prefetch_token_table
	dd	radial_gradient_token_table
	dd	rect_token_table
	dd	script_token_table
	dd	set_token_table
	dd	solid_color_token_table
	dd	stop_token_table
	dd	svg_token_table
	dd	switch_token_table
	dd	tbreak_token_table
	dd	text_token_table
	dd	text_area_token_table
	dd	title_token_table
	dd	tspan_token_table
	dd	use_token_table
	dd	video_token_table
	dd	0

