all:
	pdflatex libembroidery_v0.1_manual.tex
	makeindex libembroidery_v0.1_manual.tex
	bibtex libembroidery_v0.1_manual.aux
	pdflatex libembroidery_v0.1_manual.tex
	pdflatex libembroidery_v0.1_manual.tex
	pdflatex libembroidery_v0.1_manual.tex

clean:
	rm -f libembroidery_v0.1_manual.aux
	rm -f libembroidery_v0.1_manual.bbl
	rm -f libembroidery_v0.1_manual.idx
	rm -f libembroidery_v0.1_manual.log
	rm -f libembroidery_v0.1_manual.blg
	rm -f libembroidery_v0.1_manual.ind
	rm -f libembroidery_v0.1_manual.ilg
	rm -f libembroidery_v0.1_manual.toc
	rm -f libembroidery_v0.1_manual.out
