/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbArray_ {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbArray_(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbArray_ obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbArray_(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setArc(EmbArcObject value) {
    libembroideryJNI.EmbArray__arc_set(swigCPtr, this, EmbArcObject.getCPtr(value), value);
  }

  public EmbArcObject getArc() {
    long cPtr = libembroideryJNI.EmbArray__arc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArcObject(cPtr, false);
  }

  public void setCircle(EmbCircleObject value) {
    libembroideryJNI.EmbArray__circle_set(swigCPtr, this, EmbCircleObject.getCPtr(value), value);
  }

  public EmbCircleObject getCircle() {
    long cPtr = libembroideryJNI.EmbArray__circle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbCircleObject(cPtr, false);
  }

  public void setColor(EmbColor value) {
    libembroideryJNI.EmbArray__color_set(swigCPtr, this, EmbColor.getCPtr(value), value);
  }

  public EmbColor getColor() {
    long cPtr = libembroideryJNI.EmbArray__color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbColor(cPtr, false);
  }

  public void setEllipse(EmbEllipseObject value) {
    libembroideryJNI.EmbArray__ellipse_set(swigCPtr, this, EmbEllipseObject.getCPtr(value), value);
  }

  public EmbEllipseObject getEllipse() {
    long cPtr = libembroideryJNI.EmbArray__ellipse_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbEllipseObject(cPtr, false);
  }

  public void setFlag(SWIGTYPE_p_int value) {
    libembroideryJNI.EmbArray__flag_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getFlag() {
    long cPtr = libembroideryJNI.EmbArray__flag_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setPath(SWIGTYPE_p_p_EmbPathObject_ value) {
    libembroideryJNI.EmbArray__path_set(swigCPtr, this, SWIGTYPE_p_p_EmbPathObject_.getCPtr(value));
  }

  public SWIGTYPE_p_p_EmbPathObject_ getPath() {
    long cPtr = libembroideryJNI.EmbArray__path_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_EmbPathObject_(cPtr, false);
  }

  public void setPoint(EmbPointObject value) {
    libembroideryJNI.EmbArray__point_set(swigCPtr, this, EmbPointObject.getCPtr(value), value);
  }

  public EmbPointObject getPoint() {
    long cPtr = libembroideryJNI.EmbArray__point_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbPointObject(cPtr, false);
  }

  public void setLine(EmbLineObject value) {
    libembroideryJNI.EmbArray__line_set(swigCPtr, this, EmbLineObject.getCPtr(value), value);
  }

  public EmbLineObject getLine() {
    long cPtr = libembroideryJNI.EmbArray__line_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbLineObject(cPtr, false);
  }

  public void setPolygon(SWIGTYPE_p_p_EmbPolygonObject_ value) {
    libembroideryJNI.EmbArray__polygon_set(swigCPtr, this, SWIGTYPE_p_p_EmbPolygonObject_.getCPtr(value));
  }

  public SWIGTYPE_p_p_EmbPolygonObject_ getPolygon() {
    long cPtr = libembroideryJNI.EmbArray__polygon_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_EmbPolygonObject_(cPtr, false);
  }

  public void setPolyline(SWIGTYPE_p_p_EmbPolylineObject_ value) {
    libembroideryJNI.EmbArray__polyline_set(swigCPtr, this, SWIGTYPE_p_p_EmbPolylineObject_.getCPtr(value));
  }

  public SWIGTYPE_p_p_EmbPolylineObject_ getPolyline() {
    long cPtr = libembroideryJNI.EmbArray__polyline_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_EmbPolylineObject_(cPtr, false);
  }

  public void setRect(EmbRectObject value) {
    libembroideryJNI.EmbArray__rect_set(swigCPtr, this, EmbRectObject.getCPtr(value), value);
  }

  public EmbRectObject getRect() {
    long cPtr = libembroideryJNI.EmbArray__rect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbRectObject(cPtr, false);
  }

  public void setSpline(EmbSplineObject value) {
    libembroideryJNI.EmbArray__spline_set(swigCPtr, this, EmbSplineObject.getCPtr(value), value);
  }

  public EmbSplineObject getSpline() {
    long cPtr = libembroideryJNI.EmbArray__spline_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbSplineObject(cPtr, false);
  }

  public void setStitch(EmbStitch value) {
    libembroideryJNI.EmbArray__stitch_set(swigCPtr, this, EmbStitch.getCPtr(value), value);
  }

  public EmbStitch getStitch() {
    long cPtr = libembroideryJNI.EmbArray__stitch_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbStitch(cPtr, false);
  }

  public void setThread(EmbThread value) {
    libembroideryJNI.EmbArray__thread_set(swigCPtr, this, EmbThread.getCPtr(value), value);
  }

  public EmbThread getThread() {
    long cPtr = libembroideryJNI.EmbArray__thread_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbThread(cPtr, false);
  }

  public void setVector(EmbVector value) {
    libembroideryJNI.EmbArray__vector_set(swigCPtr, this, EmbVector.getCPtr(value), value);
  }

  public EmbVector getVector() {
    long cPtr = libembroideryJNI.EmbArray__vector_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbVector(cPtr, false);
  }

  public void setCount(int value) {
    libembroideryJNI.EmbArray__count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return libembroideryJNI.EmbArray__count_get(swigCPtr, this);
  }

  public void setLength(int value) {
    libembroideryJNI.EmbArray__length_set(swigCPtr, this, value);
  }

  public int getLength() {
    return libembroideryJNI.EmbArray__length_get(swigCPtr, this);
  }

  public void setType(int value) {
    libembroideryJNI.EmbArray__type_set(swigCPtr, this, value);
  }

  public int getType() {
    return libembroideryJNI.EmbArray__type_get(swigCPtr, this);
  }

  public EmbArray_() {
    this(libembroideryJNI.new_EmbArray_(), true);
  }

}
