/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbArc {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbArc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbArc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbArc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStart(EmbVector value) {
    libembroideryJNI.EmbArc_start_set(swigCPtr, this, EmbVector.getCPtr(value), value);
  }

  public EmbVector getStart() {
    long cPtr = libembroideryJNI.EmbArc_start_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbVector(cPtr, false);
  }

  public void setMid(EmbVector value) {
    libembroideryJNI.EmbArc_mid_set(swigCPtr, this, EmbVector.getCPtr(value), value);
  }

  public EmbVector getMid() {
    long cPtr = libembroideryJNI.EmbArc_mid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbVector(cPtr, false);
  }

  public void setEnd(EmbVector value) {
    libembroideryJNI.EmbArc_end_set(swigCPtr, this, EmbVector.getCPtr(value), value);
  }

  public EmbVector getEnd() {
    long cPtr = libembroideryJNI.EmbArc_end_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbVector(cPtr, false);
  }

  public EmbArc() {
    this(libembroideryJNI.new_EmbArc(), true);
  }

}
