/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbBezier {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbBezier(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbBezier obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbBezier(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStartX(double value) {
    libembroideryJNI.EmbBezier_startX_set(swigCPtr, this, value);
  }

  public double getStartX() {
    return libembroideryJNI.EmbBezier_startX_get(swigCPtr, this);
  }

  public void setStartY(double value) {
    libembroideryJNI.EmbBezier_startY_set(swigCPtr, this, value);
  }

  public double getStartY() {
    return libembroideryJNI.EmbBezier_startY_get(swigCPtr, this);
  }

  public void setControl1X(double value) {
    libembroideryJNI.EmbBezier_control1X_set(swigCPtr, this, value);
  }

  public double getControl1X() {
    return libembroideryJNI.EmbBezier_control1X_get(swigCPtr, this);
  }

  public void setControl1Y(double value) {
    libembroideryJNI.EmbBezier_control1Y_set(swigCPtr, this, value);
  }

  public double getControl1Y() {
    return libembroideryJNI.EmbBezier_control1Y_get(swigCPtr, this);
  }

  public void setControl2X(double value) {
    libembroideryJNI.EmbBezier_control2X_set(swigCPtr, this, value);
  }

  public double getControl2X() {
    return libembroideryJNI.EmbBezier_control2X_get(swigCPtr, this);
  }

  public void setControl2Y(double value) {
    libembroideryJNI.EmbBezier_control2Y_set(swigCPtr, this, value);
  }

  public double getControl2Y() {
    return libembroideryJNI.EmbBezier_control2Y_get(swigCPtr, this);
  }

  public void setEndX(double value) {
    libembroideryJNI.EmbBezier_endX_set(swigCPtr, this, value);
  }

  public double getEndX() {
    return libembroideryJNI.EmbBezier_endX_get(swigCPtr, this);
  }

  public void setEndY(double value) {
    libembroideryJNI.EmbBezier_endY_set(swigCPtr, this, value);
  }

  public double getEndY() {
    return libembroideryJNI.EmbBezier_endY_get(swigCPtr, this);
  }

  public EmbBezier() {
    this(libembroideryJNI.new_EmbBezier(), true);
  }

}
