/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbCircle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbCircle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbCircle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbCircle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCenter(EmbVector value) {
    libembroideryJNI.EmbCircle_center_set(swigCPtr, this, EmbVector.getCPtr(value), value);
  }

  public EmbVector getCenter() {
    long cPtr = libembroideryJNI.EmbCircle_center_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbVector(cPtr, false);
  }

  public void setRadius(double value) {
    libembroideryJNI.EmbCircle_radius_set(swigCPtr, this, value);
  }

  public double getRadius() {
    return libembroideryJNI.EmbCircle_radius_get(swigCPtr, this);
  }

  public EmbCircle() {
    this(libembroideryJNI.new_EmbCircle(), true);
  }

}
