/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbColor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbColor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbColor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbColor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setR(short value) {
    libembroideryJNI.EmbColor_r_set(swigCPtr, this, value);
  }

  public short getR() {
    return libembroideryJNI.EmbColor_r_get(swigCPtr, this);
  }

  public void setG(short value) {
    libembroideryJNI.EmbColor_g_set(swigCPtr, this, value);
  }

  public short getG() {
    return libembroideryJNI.EmbColor_g_get(swigCPtr, this);
  }

  public void setB(short value) {
    libembroideryJNI.EmbColor_b_set(swigCPtr, this, value);
  }

  public short getB() {
    return libembroideryJNI.EmbColor_b_get(swigCPtr, this);
  }

  public EmbColor() {
    this(libembroideryJNI.new_EmbColor(), true);
  }

}
