/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbEllipseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbEllipseObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbEllipseObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbEllipseObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEllipse(EmbEllipse value) {
    libembroideryJNI.EmbEllipseObject_ellipse_set(swigCPtr, this, EmbEllipse.getCPtr(value), value);
  }

  public EmbEllipse getEllipse() {
    long cPtr = libembroideryJNI.EmbEllipseObject_ellipse_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbEllipse(cPtr, false);
  }

  public void setRotation(double value) {
    libembroideryJNI.EmbEllipseObject_rotation_set(swigCPtr, this, value);
  }

  public double getRotation() {
    return libembroideryJNI.EmbEllipseObject_rotation_get(swigCPtr, this);
  }

  public void setLineType(int value) {
    libembroideryJNI.EmbEllipseObject_lineType_set(swigCPtr, this, value);
  }

  public int getLineType() {
    return libembroideryJNI.EmbEllipseObject_lineType_get(swigCPtr, this);
  }

  public void setColor(EmbColor value) {
    libembroideryJNI.EmbEllipseObject_color_set(swigCPtr, this, EmbColor.getCPtr(value), value);
  }

  public EmbColor getColor() {
    long cPtr = libembroideryJNI.EmbEllipseObject_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbColor(cPtr, false);
  }

  public EmbEllipseObject() {
    this(libembroideryJNI.new_EmbEllipseObject(), true);
  }

}
