/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbEllipse {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbEllipse(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbEllipse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbEllipse(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCenterX(double value) {
    libembroideryJNI.EmbEllipse_centerX_set(swigCPtr, this, value);
  }

  public double getCenterX() {
    return libembroideryJNI.EmbEllipse_centerX_get(swigCPtr, this);
  }

  public void setCenterY(double value) {
    libembroideryJNI.EmbEllipse_centerY_set(swigCPtr, this, value);
  }

  public double getCenterY() {
    return libembroideryJNI.EmbEllipse_centerY_get(swigCPtr, this);
  }

  public void setRadiusX(double value) {
    libembroideryJNI.EmbEllipse_radiusX_set(swigCPtr, this, value);
  }

  public double getRadiusX() {
    return libembroideryJNI.EmbEllipse_radiusX_get(swigCPtr, this);
  }

  public void setRadiusY(double value) {
    libembroideryJNI.EmbEllipse_radiusY_set(swigCPtr, this, value);
  }

  public double getRadiusY() {
    return libembroideryJNI.EmbEllipse_radiusY_get(swigCPtr, this);
  }

  public EmbEllipse() {
    this(libembroideryJNI.new_EmbEllipse(), true);
  }

}
