/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbFormatList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbFormatList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbFormatList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbFormatList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setExtension(String value) {
    libembroideryJNI.EmbFormatList_extension_set(swigCPtr, this, value);
  }

  public String getExtension() {
    return libembroideryJNI.EmbFormatList_extension_get(swigCPtr, this);
  }

  public void setDescription(String value) {
    libembroideryJNI.EmbFormatList_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return libembroideryJNI.EmbFormatList_description_get(swigCPtr, this);
  }

  public void setReader_state(char value) {
    libembroideryJNI.EmbFormatList_reader_state_set(swigCPtr, this, value);
  }

  public char getReader_state() {
    return libembroideryJNI.EmbFormatList_reader_state_get(swigCPtr, this);
  }

  public void setWriter_state(char value) {
    libembroideryJNI.EmbFormatList_writer_state_set(swigCPtr, this, value);
  }

  public char getWriter_state() {
    return libembroideryJNI.EmbFormatList_writer_state_get(swigCPtr, this);
  }

  public void setType(int value) {
    libembroideryJNI.EmbFormatList_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return libembroideryJNI.EmbFormatList_type_get(swigCPtr, this);
  }

  public void setColor_only(int value) {
    libembroideryJNI.EmbFormatList_color_only_set(swigCPtr, this, value);
  }

  public int getColor_only() {
    return libembroideryJNI.EmbFormatList_color_only_get(swigCPtr, this);
  }

  public void setCheck_for_color_file(int value) {
    libembroideryJNI.EmbFormatList_check_for_color_file_set(swigCPtr, this, value);
  }

  public int getCheck_for_color_file() {
    return libembroideryJNI.EmbFormatList_check_for_color_file_get(swigCPtr, this);
  }

  public void setWrite_external_color_file(int value) {
    libembroideryJNI.EmbFormatList_write_external_color_file_set(swigCPtr, this, value);
  }

  public int getWrite_external_color_file() {
    return libembroideryJNI.EmbFormatList_write_external_color_file_get(swigCPtr, this);
  }

  public EmbFormatList() {
    this(libembroideryJNI.new_EmbFormatList(), true);
  }

}
