/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbHoop {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbHoop(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbHoop obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbHoop(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWidth(double value) {
    libembroideryJNI.EmbHoop_width_set(swigCPtr, this, value);
  }

  public double getWidth() {
    return libembroideryJNI.EmbHoop_width_get(swigCPtr, this);
  }

  public void setHeight(double value) {
    libembroideryJNI.EmbHoop_height_set(swigCPtr, this, value);
  }

  public double getHeight() {
    return libembroideryJNI.EmbHoop_height_get(swigCPtr, this);
  }

  public EmbHoop() {
    this(libembroideryJNI.new_EmbHoop(), true);
  }

}
