/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbLineObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbLineObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbLineObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbLineObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLine(EmbLine value) {
    libembroideryJNI.EmbLineObject_line_set(swigCPtr, this, EmbLine.getCPtr(value), value);
  }

  public EmbLine getLine() {
    long cPtr = libembroideryJNI.EmbLineObject_line_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbLine(cPtr, false);
  }

  public void setLineType(int value) {
    libembroideryJNI.EmbLineObject_lineType_set(swigCPtr, this, value);
  }

  public int getLineType() {
    return libembroideryJNI.EmbLineObject_lineType_get(swigCPtr, this);
  }

  public void setColor(EmbColor value) {
    libembroideryJNI.EmbLineObject_color_set(swigCPtr, this, EmbColor.getCPtr(value), value);
  }

  public EmbColor getColor() {
    long cPtr = libembroideryJNI.EmbLineObject_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbColor(cPtr, false);
  }

  public EmbLineObject() {
    this(libembroideryJNI.new_EmbLineObject(), true);
  }

}
