/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbLayer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbLayer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbLayer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbLayer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setColor(EmbColor value) {
    libembroideryJNI.EmbLayer_color_set(swigCPtr, this, EmbColor.getCPtr(value), value);
  }

  public EmbColor getColor() {
    long cPtr = libembroideryJNI.EmbLayer_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbColor(cPtr, false);
  }

  public String getName() {
    return libembroideryJNI.EmbLayer_name_get(swigCPtr, this);
  }

  public EmbLayer() {
    this(libembroideryJNI.new_EmbLayer(), true);
  }

}
