/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbPattern {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbPattern(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbPattern obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbPattern(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSettings(EmbSettings value) {
    libembroideryJNI.EmbPattern_settings_set(swigCPtr, this, EmbSettings.getCPtr(value), value);
  }

  public EmbSettings getSettings() {
    long cPtr = libembroideryJNI.EmbPattern_settings_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbSettings(cPtr, false);
  }

  public void setHoop(EmbHoop value) {
    libembroideryJNI.EmbPattern_hoop_set(swigCPtr, this, EmbHoop.getCPtr(value), value);
  }

  public EmbHoop getHoop() {
    long cPtr = libembroideryJNI.EmbPattern_hoop_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbHoop(cPtr, false);
  }

  public void setStitchList(EmbArray_ value) {
    libembroideryJNI.EmbPattern_stitchList_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getStitchList() {
    long cPtr = libembroideryJNI.EmbPattern_stitchList_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public void setThreads(EmbArray_ value) {
    libembroideryJNI.EmbPattern_threads_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getThreads() {
    long cPtr = libembroideryJNI.EmbPattern_threads_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public void setArcs(EmbArray_ value) {
    libembroideryJNI.EmbPattern_arcs_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getArcs() {
    long cPtr = libembroideryJNI.EmbPattern_arcs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public void setCircles(EmbArray_ value) {
    libembroideryJNI.EmbPattern_circles_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getCircles() {
    long cPtr = libembroideryJNI.EmbPattern_circles_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public void setEllipses(EmbArray_ value) {
    libembroideryJNI.EmbPattern_ellipses_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getEllipses() {
    long cPtr = libembroideryJNI.EmbPattern_ellipses_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public void setLines(EmbArray_ value) {
    libembroideryJNI.EmbPattern_lines_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getLines() {
    long cPtr = libembroideryJNI.EmbPattern_lines_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public void setPaths(EmbArray_ value) {
    libembroideryJNI.EmbPattern_paths_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getPaths() {
    long cPtr = libembroideryJNI.EmbPattern_paths_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public void setPoints(EmbArray_ value) {
    libembroideryJNI.EmbPattern_points_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getPoints() {
    long cPtr = libembroideryJNI.EmbPattern_points_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public void setPolygons(EmbArray_ value) {
    libembroideryJNI.EmbPattern_polygons_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getPolygons() {
    long cPtr = libembroideryJNI.EmbPattern_polygons_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public void setPolylines(EmbArray_ value) {
    libembroideryJNI.EmbPattern_polylines_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getPolylines() {
    long cPtr = libembroideryJNI.EmbPattern_polylines_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public void setRects(EmbArray_ value) {
    libembroideryJNI.EmbPattern_rects_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getRects() {
    long cPtr = libembroideryJNI.EmbPattern_rects_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public void setSplines(EmbArray_ value) {
    libembroideryJNI.EmbPattern_splines_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getSplines() {
    long cPtr = libembroideryJNI.EmbPattern_splines_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public void setCurrentColorIndex(int value) {
    libembroideryJNI.EmbPattern_currentColorIndex_set(swigCPtr, this, value);
  }

  public int getCurrentColorIndex() {
    return libembroideryJNI.EmbPattern_currentColorIndex_get(swigCPtr, this);
  }

  public EmbPattern() {
    this(libembroideryJNI.new_EmbPattern(), true);
  }

}
