/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbPointObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbPointObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbPointObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbPointObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPoint(EmbVector value) {
    libembroideryJNI.EmbPointObject_point_set(swigCPtr, this, EmbVector.getCPtr(value), value);
  }

  public EmbVector getPoint() {
    long cPtr = libembroideryJNI.EmbPointObject_point_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbVector(cPtr, false);
  }

  public void setLineType(int value) {
    libembroideryJNI.EmbPointObject_lineType_set(swigCPtr, this, value);
  }

  public int getLineType() {
    return libembroideryJNI.EmbPointObject_lineType_get(swigCPtr, this);
  }

  public void setColor(EmbColor value) {
    libembroideryJNI.EmbPointObject_color_set(swigCPtr, this, EmbColor.getCPtr(value), value);
  }

  public EmbColor getColor() {
    long cPtr = libembroideryJNI.EmbPointObject_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbColor(cPtr, false);
  }

  public EmbPointObject() {
    this(libembroideryJNI.new_EmbPointObject(), true);
  }

}
