/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbPolylineObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbPolylineObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbPolylineObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbPolylineObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPointList(EmbArray_ value) {
    libembroideryJNI.EmbPolylineObject_pointList_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getPointList() {
    long cPtr = libembroideryJNI.EmbPolylineObject_pointList_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public void setLineType(int value) {
    libembroideryJNI.EmbPolylineObject_lineType_set(swigCPtr, this, value);
  }

  public int getLineType() {
    return libembroideryJNI.EmbPolylineObject_lineType_get(swigCPtr, this);
  }

  public void setColor(EmbColor value) {
    libembroideryJNI.EmbPolylineObject_color_set(swigCPtr, this, EmbColor.getCPtr(value), value);
  }

  public EmbColor getColor() {
    long cPtr = libembroideryJNI.EmbPolylineObject_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbColor(cPtr, false);
  }

  public EmbPolylineObject() {
    this(libembroideryJNI.new_EmbPolylineObject(), true);
  }

}
