/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbRectObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbRectObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbRectObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbRectObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRect(EmbRect value) {
    libembroideryJNI.EmbRectObject_rect_set(swigCPtr, this, EmbRect.getCPtr(value), value);
  }

  public EmbRect getRect() {
    long cPtr = libembroideryJNI.EmbRectObject_rect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbRect(cPtr, false);
  }

  public void setRotation(double value) {
    libembroideryJNI.EmbRectObject_rotation_set(swigCPtr, this, value);
  }

  public double getRotation() {
    return libembroideryJNI.EmbRectObject_rotation_get(swigCPtr, this);
  }

  public void setRadius(double value) {
    libembroideryJNI.EmbRectObject_radius_set(swigCPtr, this, value);
  }

  public double getRadius() {
    return libembroideryJNI.EmbRectObject_radius_get(swigCPtr, this);
  }

  public void setLineType(int value) {
    libembroideryJNI.EmbRectObject_lineType_set(swigCPtr, this, value);
  }

  public int getLineType() {
    return libembroideryJNI.EmbRectObject_lineType_get(swigCPtr, this);
  }

  public void setColor(EmbColor value) {
    libembroideryJNI.EmbRectObject_color_set(swigCPtr, this, EmbColor.getCPtr(value), value);
  }

  public EmbColor getColor() {
    long cPtr = libembroideryJNI.EmbRectObject_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbColor(cPtr, false);
  }

  public EmbRectObject() {
    this(libembroideryJNI.new_EmbRectObject(), true);
  }

}
