/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbRect {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbRect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbRect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbRect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTop(double value) {
    libembroideryJNI.EmbRect_top_set(swigCPtr, this, value);
  }

  public double getTop() {
    return libembroideryJNI.EmbRect_top_get(swigCPtr, this);
  }

  public void setLeft(double value) {
    libembroideryJNI.EmbRect_left_set(swigCPtr, this, value);
  }

  public double getLeft() {
    return libembroideryJNI.EmbRect_left_get(swigCPtr, this);
  }

  public void setBottom(double value) {
    libembroideryJNI.EmbRect_bottom_set(swigCPtr, this, value);
  }

  public double getBottom() {
    return libembroideryJNI.EmbRect_bottom_get(swigCPtr, this);
  }

  public void setRight(double value) {
    libembroideryJNI.EmbRect_right_set(swigCPtr, this, value);
  }

  public double getRight() {
    return libembroideryJNI.EmbRect_right_get(swigCPtr, this);
  }

  public EmbRect() {
    this(libembroideryJNI.new_EmbRect(), true);
  }

}
