/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbSplineObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbSplineObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbSplineObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbSplineObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBezier(EmbBezier value) {
    libembroideryJNI.EmbSplineObject_bezier_set(swigCPtr, this, EmbBezier.getCPtr(value), value);
  }

  public EmbBezier getBezier() {
    long cPtr = libembroideryJNI.EmbSplineObject_bezier_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbBezier(cPtr, false);
  }

  public void setNext(EmbSplineObject value) {
    libembroideryJNI.EmbSplineObject_next_set(swigCPtr, this, EmbSplineObject.getCPtr(value), value);
  }

  public EmbSplineObject getNext() {
    long cPtr = libembroideryJNI.EmbSplineObject_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbSplineObject(cPtr, false);
  }

  public void setLineType(int value) {
    libembroideryJNI.EmbSplineObject_lineType_set(swigCPtr, this, value);
  }

  public int getLineType() {
    return libembroideryJNI.EmbSplineObject_lineType_get(swigCPtr, this);
  }

  public void setColor(EmbColor value) {
    libembroideryJNI.EmbSplineObject_color_set(swigCPtr, this, EmbColor.getCPtr(value), value);
  }

  public EmbColor getColor() {
    long cPtr = libembroideryJNI.EmbSplineObject_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbColor(cPtr, false);
  }

  public EmbSplineObject() {
    this(libembroideryJNI.new_EmbSplineObject(), true);
  }

}
