/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbSatinOutline {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbSatinOutline(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbSatinOutline obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbSatinOutline(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLength(int value) {
    libembroideryJNI.EmbSatinOutline_length_set(swigCPtr, this, value);
  }

  public int getLength() {
    return libembroideryJNI.EmbSatinOutline_length_get(swigCPtr, this);
  }

  public void setSide1(EmbArray_ value) {
    libembroideryJNI.EmbSatinOutline_side1_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getSide1() {
    long cPtr = libembroideryJNI.EmbSatinOutline_side1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public void setSide2(EmbArray_ value) {
    libembroideryJNI.EmbSatinOutline_side2_set(swigCPtr, this, EmbArray_.getCPtr(value), value);
  }

  public EmbArray_ getSide2() {
    long cPtr = libembroideryJNI.EmbSatinOutline_side2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbArray_(cPtr, false);
  }

  public EmbSatinOutline() {
    this(libembroideryJNI.new_EmbSatinOutline(), true);
  }

}
