/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbStitch {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbStitch(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbStitch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbStitch(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFlags(int value) {
    libembroideryJNI.EmbStitch_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return libembroideryJNI.EmbStitch_flags_get(swigCPtr, this);
  }

  public void setX(double value) {
    libembroideryJNI.EmbStitch_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return libembroideryJNI.EmbStitch_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    libembroideryJNI.EmbStitch_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return libembroideryJNI.EmbStitch_y_get(swigCPtr, this);
  }

  public void setColor(int value) {
    libembroideryJNI.EmbStitch_color_set(swigCPtr, this, value);
  }

  public int getColor() {
    return libembroideryJNI.EmbStitch_color_get(swigCPtr, this);
  }

  public EmbStitch() {
    this(libembroideryJNI.new_EmbStitch(), true);
  }

}
