/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDstJumpsPerTrim(long value) {
    libembroideryJNI.EmbSettings_dstJumpsPerTrim_set(swigCPtr, this, value);
  }

  public long getDstJumpsPerTrim() {
    return libembroideryJNI.EmbSettings_dstJumpsPerTrim_get(swigCPtr, this);
  }

  public void setHome(EmbVector value) {
    libembroideryJNI.EmbSettings_home_set(swigCPtr, this, EmbVector.getCPtr(value), value);
  }

  public EmbVector getHome() {
    long cPtr = libembroideryJNI.EmbSettings_home_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbVector(cPtr, false);
  }

  public EmbSettings() {
    this(libembroideryJNI.new_EmbSettings(), true);
  }

}
