/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbTime {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbTime(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbTime obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbTime(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setYear(long value) {
    libembroideryJNI.EmbTime_year_set(swigCPtr, this, value);
  }

  public long getYear() {
    return libembroideryJNI.EmbTime_year_get(swigCPtr, this);
  }

  public void setMonth(long value) {
    libembroideryJNI.EmbTime_month_set(swigCPtr, this, value);
  }

  public long getMonth() {
    return libembroideryJNI.EmbTime_month_get(swigCPtr, this);
  }

  public void setDay(long value) {
    libembroideryJNI.EmbTime_day_set(swigCPtr, this, value);
  }

  public long getDay() {
    return libembroideryJNI.EmbTime_day_get(swigCPtr, this);
  }

  public void setHour(long value) {
    libembroideryJNI.EmbTime_hour_set(swigCPtr, this, value);
  }

  public long getHour() {
    return libembroideryJNI.EmbTime_hour_get(swigCPtr, this);
  }

  public void setMinute(long value) {
    libembroideryJNI.EmbTime_minute_set(swigCPtr, this, value);
  }

  public long getMinute() {
    return libembroideryJNI.EmbTime_minute_get(swigCPtr, this);
  }

  public void setSecond(long value) {
    libembroideryJNI.EmbTime_second_set(swigCPtr, this, value);
  }

  public long getSecond() {
    return libembroideryJNI.EmbTime_second_get(swigCPtr, this);
  }

  public EmbTime() {
    this(libembroideryJNI.new_EmbTime(), true);
  }

}
