/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbThread {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbThread(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbThread obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbThread(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setColor(EmbColor value) {
    libembroideryJNI.EmbThread_color_set(swigCPtr, this, EmbColor.getCPtr(value), value);
  }

  public EmbColor getColor() {
    long cPtr = libembroideryJNI.EmbThread_color_get(swigCPtr, this);
    return (cPtr == 0) ? null : new EmbColor(cPtr, false);
  }

  public void setDescription(String value) {
    libembroideryJNI.EmbThread_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return libembroideryJNI.EmbThread_description_get(swigCPtr, this);
  }

  public void setCatalogNumber(String value) {
    libembroideryJNI.EmbThread_catalogNumber_set(swigCPtr, this, value);
  }

  public String getCatalogNumber() {
    return libembroideryJNI.EmbThread_catalogNumber_get(swigCPtr, this);
  }

  public EmbThread() {
    this(libembroideryJNI.new_EmbThread(), true);
  }

}
