/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmbVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmbVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmbVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_EmbVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(double value) {
    libembroideryJNI.EmbVector_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return libembroideryJNI.EmbVector_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    libembroideryJNI.EmbVector_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return libembroideryJNI.EmbVector_y_get(swigCPtr, this);
  }

  public EmbVector() {
    this(libembroideryJNI.new_EmbVector(), true);
  }

}
