/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class L_system {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected L_system(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(L_system obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_L_system(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAxiom(char value) {
    libembroideryJNI.L_system_axiom_set(swigCPtr, this, value);
  }

  public char getAxiom() {
    return libembroideryJNI.L_system_axiom_get(swigCPtr, this);
  }

  public void setAlphabet(String value) {
    libembroideryJNI.L_system_alphabet_set(swigCPtr, this, value);
  }

  public String getAlphabet() {
    return libembroideryJNI.L_system_alphabet_get(swigCPtr, this);
  }

  public void setConstants(String value) {
    libembroideryJNI.L_system_constants_set(swigCPtr, this, value);
  }

  public String getConstants() {
    return libembroideryJNI.L_system_constants_get(swigCPtr, this);
  }

  public void setRules(SWIGTYPE_p_p_char value) {
    libembroideryJNI.L_system_rules_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getRules() {
    long cPtr = libembroideryJNI.L_system_rules_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public L_system() {
    this(libembroideryJNI.new_L_system(), true);
  }

}
