/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class thread_color {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected thread_color(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(thread_color obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libembroideryJNI.delete_thread_color(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    libembroideryJNI.thread_color_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return libembroideryJNI.thread_color_name_get(swigCPtr, this);
  }

  public void setHex_code(long value) {
    libembroideryJNI.thread_color_hex_code_set(swigCPtr, this, value);
  }

  public long getHex_code() {
    return libembroideryJNI.thread_color_hex_code_get(swigCPtr, this);
  }

  public void setManufacturer_code(int value) {
    libembroideryJNI.thread_color_manufacturer_code_set(swigCPtr, this, value);
  }

  public int getManufacturer_code() {
    return libembroideryJNI.thread_color_manufacturer_code_get(swigCPtr, this);
  }

  public thread_color() {
    this(libembroideryJNI.new_thread_color(), true);
  }

}
