name: Build and Test

on:
  workflow_dispatch:

#  schedule:
#    - cron:  '30 17 * * *'

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Get repository
      uses: actions/checkout@v3

    - name: Build
      run: bash testing.sh ${{ matrix.os }}

    - name: Packager
      run: bash packager.sh ${{ matrix.os }}

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./package
