.TH "_bcf_file_difat" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_bcf_file_difat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBfatSectorCount\fP"
.br
.ti -1c
.RI "unsigned int \fBfatSectorEntries\fP [109]"
.br
.ti -1c
.RI "unsigned int \fBsectorSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB181\fP of file \fBembroidery_internal\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int fatSectorCount"

.PP
Definition at line \fB183\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned int fatSectorEntries[109]"

.PP
Definition at line \fB184\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned int sectorSize"

.PP
Definition at line \fB185\fP of file \fBembroidery_internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
