.TH "_bcf_file" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_bcf_file
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbcf_file_header\fP \fBheader\fP"
.br
.ti -1c
.RI "\fBbcf_file_difat\fP * \fBdifat\fP"
.br
.ti -1c
.RI "\fBbcf_file_fat\fP * \fBfat\fP"
.br
.ti -1c
.RI "\fBbcf_directory\fP * \fBdirectory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB244\fP of file \fBembroidery_internal\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBbcf_file_difat\fP* difat"
The header for the CompoundFile 
.PP
Definition at line \fB247\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "\fBbcf_directory\fP* directory"
The File Allocation Table for the Compound File 
.PP
Definition at line \fB249\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "\fBbcf_file_fat\fP* fat"
The 'Double Indirect FAT' for the CompoundFile 
.PP
Definition at line \fB248\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "\fBbcf_file_header\fP header"

.PP
Definition at line \fB246\fP of file \fBembroidery_internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
