.TH "_bcf_directory_entry" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_bcf_directory_entry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBdirectoryEntryName\fP [32]"
.br
.ti -1c
.RI "unsigned short \fBdirectoryEntryNameLength\fP"
.br
.ti -1c
.RI "unsigned char \fBobjectType\fP"
.br
.ti -1c
.RI "unsigned char \fBcolorFlag\fP"
.br
.ti -1c
.RI "unsigned int \fBleftSiblingId\fP"
.br
.ti -1c
.RI "unsigned int \fBrightSiblingId\fP"
.br
.ti -1c
.RI "unsigned int \fBchildId\fP"
.br
.ti -1c
.RI "unsigned char \fBCLSID\fP [16]"
.br
.ti -1c
.RI "unsigned int \fBstateBits\fP"
.br
.ti -1c
.RI "\fBEmbTime\fP \fBcreationTime\fP"
.br
.ti -1c
.RI "\fBEmbTime\fP \fBmodifiedTime\fP"
.br
.ti -1c
.RI "unsigned int \fBstartingSectorLocation\fP"
.br
.ti -1c
.RI "unsigned long \fBstreamSize\fP"
.br
.ti -1c
.RI "unsigned int \fBstreamSizeHigh\fP"
.br
.ti -1c
.RI "struct \fB_bcf_directory_entry\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB195\fP of file \fBembroidery_internal\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int childId"

.PP
Definition at line \fB203\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned char CLSID[16]"

.PP
Definition at line \fB204\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned char colorFlag"

.PP
Definition at line \fB200\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "\fBEmbTime\fP creationTime"

.PP
Definition at line \fB206\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "char directoryEntryName[32]"

.PP
Definition at line \fB197\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned short directoryEntryNameLength"

.PP
Definition at line \fB198\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned int leftSiblingId"

.PP
Definition at line \fB201\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "\fBEmbTime\fP modifiedTime"

.PP
Definition at line \fB207\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "struct \fB_bcf_directory_entry\fP* next"

.PP
Definition at line \fB211\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned char objectType"

.PP
Definition at line \fB199\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned int rightSiblingId"

.PP
Definition at line \fB202\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned int startingSectorLocation"

.PP
Definition at line \fB208\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned int stateBits"

.PP
Definition at line \fB205\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned long streamSize"

.PP
Definition at line \fB209\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned int streamSizeHigh"

.PP
Definition at line \fB210\fP of file \fBembroidery_internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
