.TH "_bcf_file_fat" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_bcf_file_fat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfatEntryCount\fP"
.br
.ti -1c
.RI "unsigned int \fBfatEntries\fP [255]"
.br
.ti -1c
.RI "unsigned int \fBnumberOfEntriesInFatSector\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB188\fP of file \fBembroidery_internal\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int fatEntries[255]"

.PP
Definition at line \fB191\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int fatEntryCount"

.PP
Definition at line \fB190\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned int numberOfEntriesInFatSector"

.PP
Definition at line \fB192\fP of file \fBembroidery_internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
