.TH "_vp3Hoop" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_vp3Hoop
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBright\fP"
.br
.ti -1c
.RI "int \fBbottom\fP"
.br
.ti -1c
.RI "int \fBleft\fP"
.br
.ti -1c
.RI "int \fBtop\fP"
.br
.ti -1c
.RI "int \fBthreadLength\fP"
.br
.ti -1c
.RI "char \fBunknown2\fP"
.br
.ti -1c
.RI "unsigned char \fBnumberOfColors\fP"
.br
.ti -1c
.RI "unsigned short \fBunknown3\fP"
.br
.ti -1c
.RI "int \fBunknown4\fP"
.br
.ti -1c
.RI "int \fBnumberOfBytesRemaining\fP"
.br
.ti -1c
.RI "int \fBxOffset\fP"
.br
.ti -1c
.RI "int \fByOffset\fP"
.br
.ti -1c
.RI "unsigned char \fBbyte1\fP"
.br
.ti -1c
.RI "unsigned char \fBbyte2\fP"
.br
.ti -1c
.RI "unsigned char \fBbyte3\fP"
.br
.ti -1c
.RI "int \fBright2\fP"
.br
.ti -1c
.RI "int \fBleft2\fP"
.br
.ti -1c
.RI "int \fBbottom2\fP"
.br
.ti -1c
.RI "int \fBtop2\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB252\fP of file \fBembroidery_internal\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int bottom"

.PP
Definition at line \fB255\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int bottom2"

.PP
Definition at line \fB275\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned char byte1"

.PP
Definition at line \fB268\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned char byte2"

.PP
Definition at line \fB269\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned char byte3"

.PP
Definition at line \fB270\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int height"

.PP
Definition at line \fB279\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int left"

.PP
Definition at line \fB256\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int left2"

.PP
Definition at line \fB274\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int numberOfBytesRemaining"

.PP
Definition at line \fB263\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned char numberOfColors"

.PP
Definition at line \fB260\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int right"

.PP
Definition at line \fB254\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int right2"

.PP
Definition at line \fB273\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int threadLength"

.PP
Definition at line \fB258\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int top"

.PP
Definition at line \fB257\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int top2"

.PP
Definition at line \fB276\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "char unknown2"

.PP
Definition at line \fB259\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned short unknown3"

.PP
Definition at line \fB261\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int unknown4"

.PP
Definition at line \fB262\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int width"

.PP
Definition at line \fB278\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int xOffset"

.PP
Definition at line \fB265\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int yOffset"

.PP
Definition at line \fB266\fP of file \fBembroidery_internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
