.TH "src Directory Reference" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBarray\&.c\fP"
.br
.ti -1c
.RI "file \fBcompress\&.c\fP"
.br
.ti -1c
.RI "file \fBembroidery\&.h\fP"
.br
.ti -1c
.RI "file \fBembroidery_internal\&.h\fP"
.br
.ti -1c
.RI "file \fBencoding\&.c\fP"
.br
.ti -1c
.RI "file \fBfill\&.c\fP"
.br
.ti -1c
.RI "file \fBformats\&.c\fP"
.br
.ti -1c
.RI "file \fBgeometry\&.c\fP"
.br
.ti -1c
.RI "file \fBimage\&.c\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBpattern\&.c\fP"
.br
.ti -1c
.RI "file \fBthread\-color\&.c\fP"
.br
.in -1c
