.TH "Compress" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Compress
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBbit_position\fP"
.br
.ti -1c
.RI "char * \fBinput_data\fP"
.br
.ti -1c
.RI "int \fBinput_length\fP"
.br
.ti -1c
.RI "int \fBbits_total\fP"
.br
.ti -1c
.RI "int \fBblock_elements\fP"
.br
.ti -1c
.RI "\fBhuffman\fP \fBcharacter_length_huffman\fP"
.br
.ti -1c
.RI "\fBhuffman\fP \fBcharacter_huffman\fP"
.br
.ti -1c
.RI "\fBhuffman\fP \fBdistance_huffman\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB368\fP of file \fBembroidery_internal\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int bit_position"

.PP
Definition at line \fB369\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int bits_total"

.PP
Definition at line \fB372\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int block_elements"

.PP
Definition at line \fB373\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "\fBhuffman\fP character_huffman"

.PP
Definition at line \fB375\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "\fBhuffman\fP character_length_huffman"

.PP
Definition at line \fB374\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "\fBhuffman\fP distance_huffman"

.PP
Definition at line \fB376\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "char* input_data"

.PP
Definition at line \fB370\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int input_length"

.PP
Definition at line \fB371\fP of file \fBembroidery_internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
