.TH "EmbArray_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbArray_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEmbGeometry\fP * \fBgeometry\fP"
.br
.ti -1c
.RI "\fBEmbStitch\fP * \fBstitch\fP"
.br
.ti -1c
.RI "\fBEmbThread\fP * \fBthread\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB408\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int count"

.PP
Definition at line \fB412\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbGeometry\fP* geometry"

.PP
Definition at line \fB409\fP of file \fBembroidery\&.h\fP\&.
.SS "int length"

.PP
Definition at line \fB413\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbStitch\fP* stitch"

.PP
Definition at line \fB410\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbThread\fP* thread"

.PP
Definition at line \fB411\fP of file \fBembroidery\&.h\fP\&.
.SS "int type"

.PP
Definition at line \fB414\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
