.TH "EmbBezier_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbBezier_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEmbVector\fP \fBstart\fP"
.br
.ti -1c
.RI "\fBEmbVector\fP \fBcontrol1\fP"
.br
.ti -1c
.RI "\fBEmbVector\fP \fBcontrol2\fP"
.br
.ti -1c
.RI "\fBEmbVector\fP \fBend\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB367\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBEmbVector\fP control1"

.PP
Definition at line \fB369\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbVector\fP control2"

.PP
Definition at line \fB370\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbVector\fP end"

.PP
Definition at line \fB371\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbVector\fP start"

.PP
Definition at line \fB368\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
