.TH "EmbEllipse_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbEllipse_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEmbVector\fP \fBcenter\fP"
.br
.ti -1c
.RI "\fBEmbVector\fP \fBradius\fP"
.br
.ti -1c
.RI "\fBEmbReal\fP \fBrotation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB360\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBEmbVector\fP center"

.PP
Definition at line \fB362\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbVector\fP radius"

.PP
Definition at line \fB363\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbReal\fP rotation"

.PP
Definition at line \fB364\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
