.TH "EmbFormatList_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbFormatList_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBextension\fP [2+\fBEMBFORMAT_MAXEXT\fP]"
.br
.ti -1c
.RI "char \fBdescription\fP [\fBEMBFORMAT_MAXDESC\fP]"
.br
.ti -1c
.RI "char \fBreader_state\fP"
.br
.ti -1c
.RI "char \fBwriter_state\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBcolor_only\fP"
.br
.ti -1c
.RI "int \fBcheck_for_color_file\fP"
.br
.ti -1c
.RI "int \fBwrite_external_color_file\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB436\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int check_for_color_file"

.PP
Definition at line \fB444\fP of file \fBembroidery\&.h\fP\&.
.SS "int color_only"

.PP
Definition at line \fB443\fP of file \fBembroidery\&.h\fP\&.
.SS "char description[\fBEMBFORMAT_MAXDESC\fP]"

.PP
Definition at line \fB439\fP of file \fBembroidery\&.h\fP\&.
.SS "char extension[2+\fBEMBFORMAT_MAXEXT\fP]"

.PP
Definition at line \fB438\fP of file \fBembroidery\&.h\fP\&.
.SS "char reader_state"

.PP
Definition at line \fB440\fP of file \fBembroidery\&.h\fP\&.
.SS "int type"

.PP
Definition at line \fB442\fP of file \fBembroidery\&.h\fP\&.
.SS "int write_external_color_file"

.PP
Definition at line \fB445\fP of file \fBembroidery\&.h\fP\&.
.SS "char writer_state"

.PP
Definition at line \fB441\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
