.TH "EmbGeometry_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbGeometry_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBEmbArc\fP \fBarc\fP"
.br
.ti -1c
.RI "   \fBEmbCircle\fP \fBcircle\fP"
.br
.ti -1c
.RI "   \fBEmbColor\fP \fBcolor\fP"
.br
.ti -1c
.RI "   \fBEmbEllipse\fP \fBellipse\fP"
.br
.ti -1c
.RI "   \fBEmbLine\fP \fBline\fP"
.br
.ti -1c
.RI "   \fBEmbPath\fP \fBpath\fP"
.br
.ti -1c
.RI "   \fBEmbPoint\fP \fBpoint\fP"
.br
.ti -1c
.RI "   \fBEmbPolygon\fP \fBpolygon\fP"
.br
.ti -1c
.RI "   \fBEmbPolyline\fP \fBpolyline\fP"
.br
.ti -1c
.RI "   \fBEmbRect\fP \fBrect\fP"
.br
.ti -1c
.RI "   \fBEmbSpline\fP \fBspline\fP"
.br
.ti -1c
.RI "   \fBEmbVector\fP \fBvector\fP"
.br
.ti -1c
.RI "} \fBobject\fP"
.br
.ti -1c
.RI "\fBEmbStitch\fP \fBstitch\fP"
.br
.ti -1c
.RI "\fBEmbThread\fP \fBthread\fP"
.br
.ti -1c
.RI "int \fBflag\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBlineType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB385\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBEmbArc\fP arc"

.PP
Definition at line \fB387\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbCircle\fP circle"

.PP
Definition at line \fB388\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbColor\fP color"

.PP
Definition at line \fB389\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbEllipse\fP ellipse"

.PP
Definition at line \fB390\fP of file \fBembroidery\&.h\fP\&.
.SS "int flag"

.PP
Definition at line \fB402\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbLine\fP line"

.PP
Definition at line \fB391\fP of file \fBembroidery\&.h\fP\&.
.SS "int lineType"

.PP
Definition at line \fB404\fP of file \fBembroidery\&.h\fP\&.
.SS "union  { \&.\&.\&. }  object"

.SS "\fBEmbPath\fP path"

.PP
Definition at line \fB392\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbPoint\fP point"

.PP
Definition at line \fB393\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbPolygon\fP polygon"

.PP
Definition at line \fB394\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbPolyline\fP polyline"

.PP
Definition at line \fB395\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbRect\fP rect"

.PP
Definition at line \fB396\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbSpline\fP spline"

.PP
Definition at line \fB397\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbStitch\fP stitch"

.PP
Definition at line \fB400\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbThread\fP thread"

.PP
Definition at line \fB401\fP of file \fBembroidery\&.h\fP\&.
.SS "int type"

.PP
Definition at line \fB403\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbVector\fP vector"

.PP
Definition at line \fB398\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
