.TH "EmbLeaderDim_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbLeaderDim_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEmbVector\fP \fBposition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB235\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBEmbVector\fP position"

.PP
Definition at line \fB236\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
