.TH "EmbLayer_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbLayer_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [100]"
.br
.ti -1c
.RI "\fBEmbArray\fP * \fBgeometry\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB417\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBEmbArray\fP* geometry"

.PP
Definition at line \fB420\fP of file \fBembroidery\&.h\fP\&.
.SS "char name[100]"

.PP
Definition at line \fB419\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
