.TH "EmbPath_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbPath_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEmbArray\fP * \fBpointList\fP"
.br
.ti -1c
.RI "\fBEmbArray\fP * \fBflagList\fP"
.br
.ti -1c
.RI "int \fBlineType\fP"
.br
.ti -1c
.RI "\fBEmbColor\fP \fBcolor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB295\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBEmbColor\fP color"

.PP
Definition at line \fB300\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbArray\fP* flagList"

.PP
Definition at line \fB298\fP of file \fBembroidery\&.h\fP\&.
.SS "int lineType"

.PP
Definition at line \fB299\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbArray\fP* pointList"

.PP
Definition at line \fB297\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
