.TH "EmbPattern_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbPattern_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBdstJumpsPerTrim\fP"
.br
.ti -1c
.RI "\fBEmbVector\fP \fBhome\fP"
.br
.ti -1c
.RI "\fBEmbReal\fP \fBhoop_width\fP"
.br
.ti -1c
.RI "\fBEmbReal\fP \fBhoop_height\fP"
.br
.ti -1c
.RI "\fBEmbArray\fP * \fBthread_list\fP"
.br
.ti -1c
.RI "\fBEmbArray\fP * \fBstitch_list\fP"
.br
.ti -1c
.RI "\fBEmbArray\fP * \fBgeometry\fP"
.br
.ti -1c
.RI "\fBEmbLayer\fP \fBlayer\fP [\fBEMB_MAX_LAYERS\fP]"
.br
.ti -1c
.RI "int \fBcurrentColorIndex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB423\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int currentColorIndex"

.PP
Definition at line \fB433\fP of file \fBembroidery\&.h\fP\&.
.SS "unsigned int dstJumpsPerTrim"

.PP
Definition at line \fB425\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbArray\fP* geometry"

.PP
Definition at line \fB431\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbVector\fP home"

.PP
Definition at line \fB426\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbReal\fP hoop_height"

.PP
Definition at line \fB428\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbReal\fP hoop_width"

.PP
Definition at line \fB427\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbLayer\fP layer[\fBEMB_MAX_LAYERS\fP]"

.PP
Definition at line \fB432\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbArray\fP* stitch_list"

.PP
Definition at line \fB430\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbArray\fP* thread_list"

.PP
Definition at line \fB429\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
