.TH "EmbRect_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbRect_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEmbReal\fP \fBtop\fP"
.br
.ti -1c
.RI "\fBEmbReal\fP \fBleft\fP"
.br
.ti -1c
.RI "\fBEmbReal\fP \fBbottom\fP"
.br
.ti -1c
.RI "\fBEmbReal\fP \fBright\fP"
.br
.ti -1c
.RI "\fBEmbReal\fP \fBrotation\fP"
.br
.ti -1c
.RI "\fBEmbReal\fP \fBradius\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB333\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBEmbReal\fP bottom"

.PP
Definition at line \fB337\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbReal\fP left"

.PP
Definition at line \fB336\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbReal\fP radius"

.PP
Definition at line \fB340\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbReal\fP right"

.PP
Definition at line \fB338\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbReal\fP rotation"

.PP
Definition at line \fB339\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbReal\fP top"

.PP
Definition at line \fB335\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
