.TH "EmbStitch_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbStitch_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "\fBEmbReal\fP \fBx\fP"
.br
.ti -1c
.RI "\fBEmbReal\fP \fBy\fP"
.br
.ti -1c
.RI "int \fBcolor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB303\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int color"

.PP
Definition at line \fB308\fP of file \fBembroidery\&.h\fP\&.
.SS "int flags"

.PP
Definition at line \fB305\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbReal\fP x"

.PP
Definition at line \fB306\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbReal\fP y"

.PP
Definition at line \fB307\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
