.TH "EmbSatinOutline_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbSatinOutline_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "\fBEmbArray\fP * \fBside1\fP"
.br
.ti -1c
.RI "\fBEmbArray\fP * \fBside2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB353\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int length"

.PP
Definition at line \fB355\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbArray\fP* side1"

.PP
Definition at line \fB356\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbArray\fP* side2"

.PP
Definition at line \fB357\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
