.TH "EmbTime_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbTime_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fByear\fP"
.br
.ti -1c
.RI "unsigned int \fBmonth\fP"
.br
.ti -1c
.RI "unsigned int \fBday\fP"
.br
.ti -1c
.RI "unsigned int \fBhour\fP"
.br
.ti -1c
.RI "unsigned int \fBminute\fP"
.br
.ti -1c
.RI "unsigned int \fBsecond\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB269\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int day"

.PP
Definition at line \fB273\fP of file \fBembroidery\&.h\fP\&.
.SS "unsigned int hour"

.PP
Definition at line \fB274\fP of file \fBembroidery\&.h\fP\&.
.SS "unsigned int minute"

.PP
Definition at line \fB275\fP of file \fBembroidery\&.h\fP\&.
.SS "unsigned int month"

.PP
Definition at line \fB272\fP of file \fBembroidery\&.h\fP\&.
.SS "unsigned int second"

.PP
Definition at line \fB276\fP of file \fBembroidery\&.h\fP\&.
.SS "unsigned int year"

.PP
Definition at line \fB271\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
