.TH "EmbVector_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmbVector_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEmbReal\fP \fBx\fP"
.br
.ti -1c
.RI "\fBEmbReal\fP \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The basic type to represent points absolutely or represent directions\&.
.PP
Positive y is up, units are in mm\&. 
.PP
Definition at line \fB194\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBEmbReal\fP x"

.PP
Definition at line \fB196\fP of file \fBembroidery\&.h\fP\&.
.SS "\fBEmbReal\fP y"

.PP
Definition at line \fB197\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
