.TH "src/geometry.c" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/geometry.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'embroidery\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBEmbGeometry\fP * \fBembGeometry_init\fP (int type_in)"
.br
.ti -1c
.RI "void \fBembGeometry_free\fP (\fBEmbGeometry\fP *obj)"
.br
.ti -1c
.RI "void \fBembGeometry_move\fP (\fBEmbGeometry\fP *obj, \fBEmbVector\fP delta)"
.br
.ti -1c
.RI "\fBEmbRect\fP \fBembGeometry_boundingRect\fP (\fBEmbGeometry\fP *obj)"
.br
.ti -1c
.RI "void \fBembGeometry_vulcanize\fP (\fBEmbGeometry\fP *obj)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBEmbRect\fP embGeometry_boundingRect (\fBEmbGeometry\fP * obj)"

.PP
Definition at line \fB102\fP of file \fBgeometry\&.c\fP\&.
.SS "void embGeometry_free (\fBEmbGeometry\fP * obj)"

.PP
Definition at line \fB63\fP of file \fBgeometry\&.c\fP\&.
.SS "\fBEmbGeometry\fP * embGeometry_init (int type_in)"

.PP
Definition at line \fB20\fP of file \fBgeometry\&.c\fP\&.
.SS "void embGeometry_move (\fBEmbGeometry\fP * obj, \fBEmbVector\fP delta)"

.PP
Definition at line \fB81\fP of file \fBgeometry\&.c\fP\&.
.SS "void embGeometry_vulcanize (\fBEmbGeometry\fP * obj)"

.PP
Definition at line \fB128\fP of file \fBgeometry\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
