.TH "Huffman" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Huffman
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdefault_value\fP"
.br
.ti -1c
.RI "int \fBlengths\fP [1000]"
.br
.ti -1c
.RI "int \fBnlengths\fP"
.br
.ti -1c
.RI "int \fBtable\fP [1000]"
.br
.ti -1c
.RI "int \fBtable_width\fP"
.br
.ti -1c
.RI "int \fBntable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB359\fP of file \fBembroidery_internal\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int default_value"

.PP
Definition at line \fB360\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int lengths[1000]"

.PP
Definition at line \fB361\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int nlengths"

.PP
Definition at line \fB362\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int ntable"

.PP
Definition at line \fB365\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int table[1000]"

.PP
Definition at line \fB363\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int table_width"

.PP
Definition at line \fB364\fP of file \fBembroidery_internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
