.TH "src/image.c" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/image.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'embroidery_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBwriteImage\fP (FILE *file, unsigned char image[][48])"
.br
.ti -1c
.RI "float \fBimage_diff\fP (unsigned char *a, unsigned char *b, int size)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "float image_diff (unsigned char * a, unsigned char * b, int size)"

.PP
Definition at line \fB54\fP of file \fBimage\&.c\fP\&.
.SS "void writeImage (FILE * file, unsigned char image[][48])"

.PP
Definition at line \fB26\fP of file \fBimage\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
