.TH "LSYSTEM" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LSYSTEM
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBaxiom\fP"
.br
.ti -1c
.RI "char * \fBalphabet\fP"
.br
.ti -1c
.RI "char * \fBconstants\fP"
.br
.ti -1c
.RI "char ** \fBrules\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB378\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char* alphabet"

.PP
Definition at line \fB380\fP of file \fBembroidery\&.h\fP\&.
.SS "char axiom"

.PP
Definition at line \fB379\fP of file \fBembroidery\&.h\fP\&.
.SS "char* constants"

.PP
Definition at line \fB381\fP of file \fBembroidery\&.h\fP\&.
.SS "char** rules"

.PP
Definition at line \fB382\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
