.TH "StxThread_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StxThread_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBcolorCode\fP"
.br
.ti -1c
.RI "char * \fBcolorName\fP"
.br
.ti -1c
.RI "char * \fBsectionName\fP"
.br
.ti -1c
.RI "\fBSubDescriptor\fP * \fBsubDescriptors\fP"
.br
.ti -1c
.RI "\fBEmbColor\fP \fBstxColor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB311\fP of file \fBembroidery_internal\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char* colorCode"

.PP
Definition at line \fB313\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "char* colorName"

.PP
Definition at line \fB314\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "char* sectionName"

.PP
Definition at line \fB315\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "\fBEmbColor\fP stxColor"

.PP
Definition at line \fB317\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "\fBSubDescriptor\fP* subDescriptors"

.PP
Definition at line \fB316\fP of file \fBembroidery_internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
