.TH "SubDescriptor_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubDescriptor_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsomeNum\fP"
.br
.ti -1c
.RI "int \fBsomeInt\fP"
.br
.ti -1c
.RI "int \fBsomeOtherInt\fP"
.br
.ti -1c
.RI "char * \fBcolorCode\fP"
.br
.ti -1c
.RI "char * \fBcolorName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB302\fP of file \fBembroidery_internal\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char* colorCode"

.PP
Definition at line \fB307\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "char* colorName"

.PP
Definition at line \fB308\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int someInt"

.PP
Definition at line \fB305\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int someNum"

.PP
Definition at line \fB304\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int someOtherInt"

.PP
Definition at line \fB306\fP of file \fBembroidery_internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
