.TH "thread_color_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thread_color_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [22]"
.br
.ti -1c
.RI "unsigned int \fBhex_code\fP"
.br
.ti -1c
.RI "int \fBmanufacturer_code\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB319\fP of file \fBembroidery\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int hex_code"

.PP
Definition at line \fB321\fP of file \fBembroidery\&.h\fP\&.
.SS "int manufacturer_code"

.PP
Definition at line \fB322\fP of file \fBembroidery\&.h\fP\&.
.SS "char name[22]"

.PP
Definition at line \fB320\fP of file \fBembroidery\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
