.TH "ThredExtension_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThredExtension_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBhoopX\fP"
.br
.ti -1c
.RI "float \fBhoopY\fP"
.br
.ti -1c
.RI "float \fBstitchGranularity\fP"
.br
.ti -1c
.RI "char \fBcreatorName\fP [50]"
.br
.ti -1c
.RI "char \fBmodifierName\fP [50]"
.br
.ti -1c
.RI "char \fBauxFormat\fP"
.br
.ti -1c
.RI "char \fBreserved\fP [31]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB291\fP of file \fBembroidery_internal\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char auxFormat"

.PP
Definition at line \fB298\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "char creatorName[50]"

.PP
Definition at line \fB296\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "float hoopX"

.PP
Definition at line \fB293\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "float hoopY"

.PP
Definition at line \fB294\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "char modifierName[50]"

.PP
Definition at line \fB297\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "char reserved[31]"

.PP
Definition at line \fB299\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "float stitchGranularity"

.PP
Definition at line \fB295\fP of file \fBembroidery_internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
