.TH "ThredHeader_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThredHeader_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBsigVersion\fP"
.br
.ti -1c
.RI "unsigned int \fBlength\fP"
.br
.ti -1c
.RI "unsigned short \fBnumStiches\fP"
.br
.ti -1c
.RI "unsigned short \fBhoopSize\fP"
.br
.ti -1c
.RI "unsigned short \fBreserved\fP [7]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB282\fP of file \fBembroidery_internal\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "unsigned short hoopSize"

.PP
Definition at line \fB287\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned int length"

.PP
Definition at line \fB285\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned short numStiches"

.PP
Definition at line \fB286\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned short reserved[7]"

.PP
Definition at line \fB288\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned int sigVersion"

.PP
Definition at line \fB284\fP of file \fBembroidery_internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
