.TH "VipHeader_" 3 "Sun Mar 19 2023" "Version 1.0.0-alpha" "Libembroidery" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VipHeader_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <embroidery_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmagicCode\fP"
.br
.ti -1c
.RI "int \fBnumberOfStitches\fP"
.br
.ti -1c
.RI "int \fBnumberOfColors\fP"
.br
.ti -1c
.RI "short \fBpostitiveXHoopSize\fP"
.br
.ti -1c
.RI "short \fBpostitiveYHoopSize\fP"
.br
.ti -1c
.RI "short \fBnegativeXHoopSize\fP"
.br
.ti -1c
.RI "short \fBnegativeYHoopSize\fP"
.br
.ti -1c
.RI "int \fBattributeOffset\fP"
.br
.ti -1c
.RI "int \fBxOffset\fP"
.br
.ti -1c
.RI "int \fByOffset\fP"
.br
.ti -1c
.RI "unsigned char \fBstringVal\fP [8]"
.br
.ti -1c
.RI "short \fBunknown\fP"
.br
.ti -1c
.RI "int \fBcolorLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB320\fP of file \fBembroidery_internal\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int attributeOffset"

.PP
Definition at line \fB328\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int colorLength"

.PP
Definition at line \fB333\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int magicCode"

.PP
Definition at line \fB321\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "short negativeXHoopSize"

.PP
Definition at line \fB326\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "short negativeYHoopSize"

.PP
Definition at line \fB327\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int numberOfColors"

.PP
Definition at line \fB323\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int numberOfStitches"

.PP
Definition at line \fB322\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "short postitiveXHoopSize"

.PP
Definition at line \fB324\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "short postitiveYHoopSize"

.PP
Definition at line \fB325\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "unsigned char stringVal[8]"

.PP
Definition at line \fB331\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "short unknown"

.PP
Definition at line \fB332\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int xOffset"

.PP
Definition at line \fB329\fP of file \fBembroidery_internal\&.h\fP\&.
.SS "int yOffset"

.PP
Definition at line \fB330\fP of file \fBembroidery_internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Libembroidery from the source code\&.
