name: Website (including dailies)

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_windows:
    name: "Build libembroidery on Windows, run tests."
    runs-on: windows-latest
    env:
      HOST_SYSTEM: windows-latest
    steps:
      - name: Get Script
        run: curl -s https://raw.githubusercontent.com/Embroidermodder/libembroidery/main/bin/build.sh -o build.sh
      - name: Build
        run: bash build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: libembroidery-windows
          path: ./libembroidery

  build_macos:
    name: "Build libembroidery on Mac OS, run tests."
    runs-on: macos-latest
    env:
      HOST_SYSTEM: macos-latest
    steps:
      - name: Get Script
        run: curl -s https://raw.githubusercontent.com/Embroidermodder/libembroidery/main/bin/build.sh -o build.sh
      - name: Build
        run: bash build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: libembroidery-macos
          path: ./libembroidery
  
  build_ubuntu:
    name: "Build libembroidery on Ubuntu, run tests."
    runs-on: ubuntu-latest
    env:
      HOST_SYSTEM: ubuntu-latest
    steps:
      - name: Get Script
        run: curl -s https://raw.githubusercontent.com/Embroidermodder/libembroidery/main/bin/build.sh -o build.sh

      - name: Build
        run: bash build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: libembroidery-ubuntu
          path: ./libembroidery
  
  website:
    runs-on: ubuntu-latest
    needs:
    - build_windows
    - build_macos
    - build_ubuntu
    name: "Build website."
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "windows-latest"

      - uses: actions/download-artifact@v4
        with:
          name: "macos-latest"

      - uses: actions/download-artifact@v4
        with:
          name: "ubuntu-latest"

      - name: Place in Downloads
        run: mv *.zip docs/html/downloads

      - name: Get Script
        run: curl -s https://raw.githubusercontent.com/Embroidermodder/libembroidery/main/bin/build_website.sh

      - name: Build
        run: bash build_website.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/html

#  deploy:
#    runs-on: ubuntu-latest
#    needs: website
#    steps:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v4
